services:
  todo-frontend:
    container_name: todo-frontend
    restart: on-failure:3
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    networks:
      - todo-network

  nginx:
    image: nginx:1.27.3
    container_name: todo-nginx-frontend
    depends_on:
      - todo-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/frontend/nginx.conf:ro
    networks:
      - todo-network

networks:
  todo-network:
    name: todo-network
