services:
  todo-database:
    image: postgres:16.6
    container_name: todo-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "todo"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - todo-network

  todo-cache:
    image: redis:7.2.5
    container_name: todo-cache
    ports:
      - "6379:6379"
    volumes:
      - todo_cache:/cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    networks:
      - todo-network

  # nginx:
  #   image: nginx:1.27.3
  #   container_name: todo-nginx-backend
  #   depends_on:
  #     - todo-backend
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/backend/nginx.conf:ro
  #   networks:
  #     - todo-network

  todo-backend:
    container_name: todo-backend
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - todo-database
      - todo-cache
    environment:
      - DATABASE_URL=postgres://postgres:password@todo-database:5432/todo?sslmode=disable
      - REDIS_URL=redis://todo-cache:6379
    networks:
      - todo-network

networks:
  todo-network:
    name: todo-network
    driver: bridge

volumes:
  todo_cache:
    name: todo-cache
  todo_data:
    name: todo-data
