apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
  artifacts:
    - image: woragis/todos-backend
      context: ../backend
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
    - image: woragis/todos-frontend
      context: ../frontend
      docker:
        dockerfile: Dockerfile.dev
        noCache: false
        pullParent: false
        squash: false
      sync:
        '**/*.ts': .
        '**/*.tsx': .
        '**/*.html': .
deploy:
  kubectl:
    manifests:
      - k8s/dev/backend-deployment.yaml
      - k8s/dev/frontend-deployment.yaml
