apiVersion: v1
kind: Pod
metadata:
  name: todos-backend-pod
  labels:
    todos: backend
  spec:
    containers:
      - name: backend
        image: woragis/todos-backend
        ports:
          - containerPort: 8080
