apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      todos: frontend
  template:
    metadata:
      labels:
        todos: frontend
    spec:
      containers:
        - name: todos-frontend
          image: woragis/todos-frontend
          ports:
            - containerPort: 5173
