apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
        - name: database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: database-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_PASSWORD
              value: postgrespassword
              # valueFrom:
              #   secretKeyRef:
              #     name: pgpassword
              #     key: PGPASSWORD
