apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <AWS_ECR_BACKEND_URL>:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
