apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: database
          image: postgres
          ports:
            - containerPort: 5432
