apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: woragis/todos-frontend
          ports:
            - containerPort: 5173
