name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: opened
    branches:
      - main

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.4.0

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm test

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test
        run: echo Testing...
      - name: Finis
        run: echo Test Successfull

  deploy-frontend:
    name: Deploy Frontend
    needs:
      - test-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Connect to AWS
        run: echo Connecting...

  deploy-backend:
    name: Deploy Backend
    needs:
      - test-backend
    runs-on: ubuntu-latest
    steps:
      - name: Connect to AWS
        run: echo Connecting...
